### ISSUE TITLE
select row no longer works

### ISSUE THREAD

**Issue by jadrake75** [jadrake75/ng-scrolling-table#94]
With the column reordering the row-selection is also broken

**Comment by Xanir** [comment]
Was row selection being done by adding click listeners to rows at the table level instead of the row level?
With the column reordering the rows are compiled last and would need to have a directive on the row itself to enable selection.

If we moved to using nz-selection-manager, as we had discussed previously, this issues should resolve itself.

**Comment by jadrake75** [comment]
this is currently fixed with the latest pull requests
